apiVersion: batch/v1
kind: Job
metadata:
  name: edward-cyclegan  # Replace with something like "${USER_NAME}-{EXP_NAME}"
  namespace: ucsd-haosulab
spec:
  ttlSecondsAfterFinished: 86400  # Wait one day to delete completed jobs
  template:
    spec:
      containers:
        - name: gpu-container
          image: isabella98/pix2pix:latest
          # imagePullPolicy: Always
          command:
            - "sh"
            - "-c"
          args:
            - "apt-get update
            && apt install git -y
            && pip install pandas
            && git clone https://github.com/edwardyang12/Cartoonify.git
            && cd Cartoonify
            && python -u main.py 50 5 4 4 /edward-slow-vol/cycleGAN/cycle128/
      "
          resources:
            requests:
              cpu: "4"
              memory: "13Gi"
              nvidia.com/gpu: "4"
            limits:
              cpu: "5"
              memory: "16Gi"
              nvidia.com/gpu: "4"
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: edward-slow-vol
              mountPath: /edward-slow-vol
      volumes:
        - name: dshm  # shared memory, required for the multi-worker dataloader
          emptyDir:
            medium: Memory
        - name: edward-slow-vol
          persistentVolumeClaim:
            claimName: edward-slow-vol
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      # - k8s-haosu-10.sdsc.optiputer.net
                      - k8s-haosu-16.sdsc.optiputer.net
                  - key: nautilus.io/group
                    operator: In
                    values:
                      - haosu
                  - key: gpu-type
                    operator: In
                    values:
                      - 1080Ti
                      - 2080Ti
  backoffLimit: 0  # The number of attempts to restart after crash
