apiVersion: v1
kind: Pod
metadata:
  name: edward-gan  # Replace with something like "${USER_NAME}-{EXP_NAME}"
  namespace: ucsd-haosulab
spec:
  containers:
    - name: gpu-container
      image: isabella98/pix2pix:latest
      # imagePullPolicy: Always
      args: ["sleep", "infinity"]
      resources:
        requests:
          cpu: "1"
          memory: "4Gi"
          nvidia.com/gpu: "1"
        limits:
          cpu: "2"
          memory: "8Gi"
          nvidia.com/gpu: "1"
      volumeMounts:
        - name: edward-fast-vol
          mountPath: /edward-fast-vol
        - name: edward-slow-vol
          mountPath: /edward-slow-vol
  volumes:
    - name: edward-fast-vol
      persistentVolumeClaim:
        claimName: edward-fast-vol
    - name: edward-slow-vol
      persistentVolumeClaim:
        claimName: edward-slow-vol
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - k8s-haosu-10.sdsc.optiputer.net
                  - k8s-haosu-16.sdsc.optiputer.net
              - key: nautilus.io/group
                operator: In
                values:
                  - haosu
              - key: gpu-type
                operator: In
                values:
                  - 1080Ti
                  - 2080Ti
#  nodeSelector:
#    kubernetes.io/hostname: "k8s-haosu-01.sdsc.optiputer.net"
